### ISSUE TITLE
Refine become_user for virtualenv var declarations

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/django_stack#8]
Many of the tasks in `tasks/django_service.yml` set `become_user: "{{ django_stack_gcorn_user }}"`. Some don't, however, and they probably should. For instance:

```
- name: Ensure environment parameters are sufficiently exported
  lineinfile:
    dest: "{{ django_stack_gcorn_home }}/{{ django_stack_app_name }}/bin/activate"
    line: "set -a"
    create: yes

- name: Ensure environment gets called upon venv activation
  lineinfile:
    dest: "{{ django_stack_gcorn_home }}/{{ django_stack_app_name }}/bin/activate"
    line: ". {{ django_stack_gcorn_home }}/{{ django_stack_app_name }}/bin/environment"
    insertafter: "^set -a"

- name: Drop credentials in virtualenv environment
  lineinfile:
    dest: "{{ django_stack_gcorn_home }}/{{ django_stack_app_name }}/bin/environment"
    line: "{{ item.key }}={{ item.value }}"
    regexp: "^{{ item.key }}="
    create: yes
  no_log: true
  with_dict: "{{ django_stack_gunicorn_default_envs|combine(django_stack_gunicorn_opt_envs) }}"
  notify: Restart Gunicorn
```

All of those are _outside_ the become_user block, which means that file perms become root:root 644, which is a big outlier:

```
# cd to <virtualenv>/bin
$ ls -l | head -n 15
total 4536
-rw-r--r-- 1 gcorn gcorn    2255 Nov 15 10:32 activate
-rw-r--r-- 1 gcorn gcorn    1261 Nov 15 10:24 activate.csh
-rw-r--r-- 1 gcorn gcorn    2474 Nov 15 10:24 activate.fish
-rw-r--r-- 1 gcorn gcorn    1129 Nov 15 10:24 activate_this.py
-rwxr-xr-x 1 gcorn gcorn     577 Nov 15 10:31 createfontdatachunk.py
-rwxr-xr-x 1 gcorn gcorn     331 Nov 15 10:26 csscapture
-rwxr-xr-x 1 gcorn gcorn     331 Nov 15 10:26 csscombine
-rwxr-xr-x 1 gcorn gcorn     327 Nov 15 10:26 cssparse
-rwxr-xr-x 1 gcorn gcorn     286 Nov 15 10:26 django-admin
-rwxr-xr-x 1 gcorn gcorn     145 Nov 15 10:26 django-admin.py
-rwxr-xr-x 1 gcorn gcorn     253 Nov 15 10:32 easy_install
-rwxr-xr-x 1 gcorn gcorn     253 Nov 15 10:32 easy_install-3.4
-rwxr-xr-x 1 gcorn gcorn    1602 Nov 15 10:31 enhancer.py
-rw-r--r-- 1 root  root      918 Nov 16 17:08 environment
```
